version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: panama
    main: ./cmd/panama
    binary: panama
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.json"

release:
  github:
    owner: yuya-takeyama
    name: panama
  draft: false
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    ### Using aqua
    ```bash
    aqua g -i yuya-takeyama/panama
    ```

    ### Using go install
    ```bash
    go install github.com/yuya-takeyama/panama/cmd/panama@latest
    ```

    ### Using Homebrew (macOS/Linux)
    ```bash
    brew install yuya-takeyama/tap/panama
    ```

    ### Binary download
    Download the appropriate binary for your platform from the assets below.

    ## Shell Integration

    Add to your shell config:
    ```bash
    # Quick workspace switcher
    pw() {
      local dir
      dir=$(panama select "$@")
      if [[ -n "$dir" ]]; then
        cd "$dir"
      fi
    }
    ```

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"