# Panama workspace finder configuration
# https://github.com/yuya-takeyama/panama

# Maximum depth to search for workspaces from the root directory
# Default: 6
max_depth: 6

# Output format for results
# Options: path, cd, json
# Default: path
format: path

# Directories to ignore during workspace search
# These directories will be skipped completely
ignored_dirs:
  - node_modules
  - .git
  - vendor
  - target
  - dist
  - build
  - .next
  - .nuxt
  - .cache
  - __pycache__
  - .terraform

# Custom workspace detection patterns
# Add file or directory patterns that indicate a workspace root
# Supports glob patterns (e.g., "*.xcodeproj", "*.workspace")
# patterns:
#   - .workspace        # Custom workspace marker file
#   - project.config    # Project-specific config file
#   - "*.xcodeproj"     # Xcode project directories
#   - workspace.json    # Nx monorepo workspace

# Specific workspace directories to search
# Uncomment and modify if you want to limit search to specific directories
# workspaces:
#   - ./projects
#   - ./packages